### PR TITLE
Update COPYING to match the LICENSE as published by FSF

### PR DESCRIPTION
**Pull request by matsl**
@tarsius PTAL 

Can these minor formatting and single word changes explain why the automatic identification of the license does not work?

### CODE REVIEW

**Comment by tarsius** [comment]
The problem was that there is no file `dvc.el` from which to extract metadata. If that file is absent then the code that could extract it from the COPYING file is also not run. I fixed this by explicitly specifying `lisp/dvc-core.el` as the "main library".

For `elgyach` it did not work because the library is named `gyach.el`. I fixed this by renaming the package.

**Comment by matsl** [comment]
OK. So updates to the LICENSE text is not actually needed for this so we should not bother about that I suppose.

**Comment by tarsius** [comment]
Yes, if you find a similar mismatch, then just send me a note about that.

Thanks for your work!

**Comment by matsl** [comment]
Hi Jonas,

> Jonas Bernoulli writes:
> Yes, if you find a similar mismatch, then just send me a note about that.

Next one is https://github.com/emacsattic/elite. I suggest rename package to elite-for-emacs.

Yours
-- 
%% Mats

**Comment by matsl** [comment]
Yet another:

https://github.com/emacsattic/elpoint -> rename to ept? (havent checked if that short name would conflict with anything.)

**Pull request merged**
